# Generated by Django 5.0 on 2024-01-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
