# Generated by Django 5.0 on 2024-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0003_alter_register_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('from_date_value', models.DateField()),
                ('to_date_value', models.DateField()),
            ],
            options={
                'db_table': 'rentcar',
            },
        ),
    ]
