# Generated by Django 5.0 on 2024-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0006_rename_location_rentcar_location1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcar',
            name='id',
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='location1',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
