# Generated by Django 5.0.1 on 2024-01-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0008_alter_rentcar_location1_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
